model_name: mistralai/Mixtral-8x7B-Instruct-v0.1
data_path: data/processed/train.jsonl
output_dir: outputs/stoic-mixtral
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
num_train_epochs: 3
learning_rate: 2e-5
